event_management/urls.py
from django.contrib import admin
from django.urls import path,include
from debug_toolbar.toolbar import debug_toolbar_urls
from events.views import home
from core.views import no_permission
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('events/', include("events.urls")),
    path('users/', include("users.urls")),
    path('no_permission', no_permission, name = 'no_permission'),


]+debug_toolbar_urls()

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import signup,signin,signout,authpage,activate_user,admin_dashboard,assign_role,create_group,group_list,dashboard,events_with_participants,delete_participant_from_any_event

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('auth/', authpage, name='authpage'),

    path('logout/', signout, name='logout'),
    path('activate/<int:user_id>/<str:token>/', activate_user, name='activate'),
    path('admin/dashboard', admin_dashboard, name='admin_dashboard'),
    path('admin/<int:user_id>/assign_role/', assign_role, name='assign_role'),
    path('admin/create_group',create_group,name='create_group'),
    path('admin/group_list/',group_list,name='group_list'),
    path('admin/events-with-participants/',events_with_participants,name='events-with-participants'),
    path('admin/delete_participant_from_any_event/<int:event_id>/<int:participant_id>/',delete_participant_from_any_event,name='delete-participant-from-any-event'),

    path('dashboard/',dashboard,name="dashboard")

]

core/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.

class Category(models.Model):
    name = models.CharField( max_length = 100)
    description = models.TextField()
    
    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField( max_length = 100)
    description = models.TextField(blank=True,null = True)
    date = models.DateField()
    time = models.TimeField()
    location = models.TextField()
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE ,
                                related_name='events' )
    participants_users = models.ManyToManyField(
        User,
        related_name="events_joined",
        blank=True
    )
    asset = models.ImageField(upload_to="events_asset",blank= True, null = True, default="default.jpg")

    
    def __str__(self):
        return self.name
    
# class Participant(models.Model):
#     name = models.CharField( max_length = 100)
#     email = models.EmailField(unique = True)
#     events = models.ManyToManyField(Event,related_name='participants')
#     is_confirmed = models.BooleanField(default=False)
    
#     def __str__(self):
#         return self.name

core/views.py
from django.shortcuts import render

# Create your views here.
def no_permission(request):
    return render(request, 'no_permission.html')

core/templates/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

</head>
<body>
    
    <footer class="bg-gray-800 text-white py-8">
        <div class="container mx-auto px-6">
            <div class="flex flex-wrap justify-between">
                <div class="w-1/4 mb-8 md:mb-0 ">
                    <h3 class="text-lg font-semibold mb-4">EventMaster</h3>
                    <p class="text-gray-400">
                        Empowering teams with efficient <br> event management solutions.
                    </p>
                </div>
                <div class="w-1/4 mb-8 md:mb-0 ">
                    <h4 class="text-lg font-semibold mb-4">Quick Links</h4>
                    <ul class="text-gray-400 space-y-2">
                        <li><a href="#" class="hover:text-white">Home</a></li>
                        <li><a href="#" class="hover:text-white">Features</a></li>
                        <li><a href="#" class="hover:text-white">About</a></li>
                        <li><a href="#" class="hover:text-white">Contact</a></li>
                    </ul>
                </div>
                <div class="w-1/4 mb-8 md:mb-0">
                    <h4 class="text-lg font-semibold mb-4">Connect</h4>
                    <ul class="text-gray-400 space-y-2">
                        <li><a href="#" class="hover:text-white">Twitter</a></li>
                        <li><a href="#" class="hover:text-white">LinkedIn</a></li>
                        <li><a href="#" class="hover:text-white">Facebook</a></li>
                    </ul>
                </div>
                <div class="w-1/4">
                    <h4 class="text-lg font-semibold mb-4">Message</h4>
                    <form class="flex">
                        <input
                            type="email"
                            placeholder="Your email"
                            class="w-full px-3 py-2 text-gray-700 bg-gray-200 rounded-l-md focus:outline-none"
                            required
                        />
                        <button
                        type="submit"
                        class="bg-blue-500 text-white px-4 py-2 rounded-r-md hover:bg-blue-600 transition duration-300"
                        >
                            Subscribe
                        </button>
                    </form>
                </div>
            </div>
            <div
                class="border-t border-gray-700 mt-12 pt-8 text-sm text-center text-gray-400"
            >
            &copy; 2026 EventMaster. All rights reserved.
            </div>
            <div class="py-3 text-center">
            <p>Event Management System</p>
            {% if user.is_authenticated %}
                {{user}}

            {% else %}
                Annonymous
            {% endif %}
        </div>
        </div>
    </footer>
</body>
</html>

core/templates/logged_header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
    <script src="{% static 'js/navbar.js' %}"></script>
</head>
<body>
    <header class="relative z-100 mx-6 px-3 py-5 flex justify-between items-center">
        {% comment %} LOGO  {% endcomment %}
        <div class="img flex justify-center items-center">
            <img src=" {% static 'images/logo1.png' %}" alt="" style="width: 50px;">
            <h1 class="text-xl font-semibold text-white">Events</h1>

        </div>

        <button id="hamburgerBtn" class="md:hidden flex flex-col gap-1 p-2">
            <span class="block w-6 h-0.5 bg-white"></span>
            <span class="block w-6 h-0.5 bg-white"></span>
            <span class="block w-6 h-0.5 bg-white"></span>
        </button>

        
        {% comment %} NAVIGATION  {% endcomment %}
        <nav class="hidden md:flex md:gap-4 items-center">
            <ul class="flex flex-col  md:flex-row gap-4  text-white">
               <a href="{% url "home" %}"> <li class="px-2 py-1 rounded-sm hover:bg-white/20">Home</li></a>
               <a href="{% url "home" %}#all-events"><li class="px-2 py-1 rounded-sm hover:bg-white/20">Explore</li></a>
               <a href="{% url "home" %}#rsvp_events"><li class="px-2 py-1 rounded-sm hover:bg-white/20">RSVP</li></a>
               
                {% if perms.events.add_category %}
                    <li class="relative z-50 px-2 py-1 rounded-sm hover:bg-white/20">
                        <div class="relative inline-block group">
                            <div class="flex items-center cursor-pointer">
                                <span class="">Category</span>
                                    
                            </div>
                            <div 
                                class="absolute right-0 w-44 rounded-md bg-slate-800 shadow-lg ring-1 ring-black/5
                                opacity-0 invisible group-hover:opacity-100 group-hover:visible
                                transition duration-150">
                                    <a href="{% url "create-category" %}" target="__<blank" class="block  px-4 py-2 text-sm hover:bg-gray-700">Create</a>
                                    <a href="{% url "category-list" %}" target="__<blank" class="block  px-4 py-2 text-sm hover:bg-gray-700">View</a>
                            </div>
                        </div>
                    </li>
                {% endif %}
                {% if perms.group.add_group %}

                <li class="relative z-50 px-2 py-1 rounded-sm hover:bg-white/20">
                        <div class="relative inline-block group">
                            <div class="flex items-center cursor-pointer">
                                <span class="">Groups</span>
                                    
                            </div>
                            <div 
                                class="absolute right-0 w-44 rounded-md bg-slate-800 shadow-lg ring-1 ring-black/5
                                opacity-0 invisible group-hover:opacity-100 group-hover:visible
                                transition duration-150">
                                    <a  href="{% url "group_list" %}" target="__<blank" class="block  px-4 py-2 text-sm hover:bg-gray-700">View</a>
                                    <a href="{% url "create_group" %}" target="__<blank" class="block  px-4 py-2 text-sm hover:bg-gray-700">Create</a>
                            </div>
                        </div>
                    </li>
                
               {% endif %}
                
               {% if perms.group.add_group %}
                <a href="{% url "organizer" %}"><li class="px-2 py-1 rounded-sm hover:bg-white/20">Organizer</li></a>
               {% endif %}
                <a href="{% url "dashboard" %}"><li class="px-2 py-1 rounded-sm hover:bg-white/20">Dashboard</li></a>
                
               
                <li>
                    <form method="POST" action="{% url "logout" %}">
                        {% csrf_token %}
                        <button type="submit" class="px-2 py-1 bg-white/30 backdrop-blur-sm rounded text-white text-center font-semibold border border-white/50 hover:bg-white/20">
                            logout
                        </button>
                    </form>
                </li>
                <a href="https://github.com/JUBAYER-AHMMED">
                    <li>
                        <button class="w-10 h-10 bg-slate-500/30 backdrop-blur-sm rounded-full text-white text-center font-semibold border border-white/50 hover:bg-slate-500">
                            J
                        </button>
                    </li>
                </a>  

            </ul>
        </nav>
    </header>
    <ul id="navMenu"
    class="hidden flex-col items-center justify-center relative z-30 gap-4
           text-white text-lg text-center md:hidden
           border backdrop-blur-sm border-white/5 bg-transparent shadow-md p-2">
        <a href="{% url "home" %}"> <li class="px-2 py-1 rounded-sm hover:bg-white/20">Home</li></a>
        <a href="{% url "home" %}#all-events"><li class="px-2 py-1 rounded-sm hover:bg-white/20">Explore</li></a>
        {% if perms.group.add_group %}
            <a href="{% url "group_list" %}"><li class="px-2 py-1 rounded-sm hover:bg-white/20">Groups</li></a>
            <a href="{% url "create_group" %}"><li class="px-2 py-1 rounded-sm hover:bg-white/20">Create Groups</li></a> 
        {% endif %}
        {% if perms.event.add_event %}
            <a href="{% url "organizer" %}"><li class="px-2 py-1 rounded-sm hover:bg-white/20">Organizer</li></a>
        {% endif %}        
        <a href="{% url "dashboard" %}"><li class="px-2 py-1 rounded-sm hover:bg-white/20">Dashboard</li></a>
        {% if perms.category.add_category %}
                    <li class="relative z-50 px-2 py-1 rounded-sm hover:bg-white/20">
                        <div class="relative inline-block group">
                            <div class="flex items-center cursor-pointer">
                                <span class="">Category</span>
                                    
                            </div>
                            <div 
                                class="absolute right-0 w-44 rounded-md bg-slate-800 shadow-lg ring-1 ring-black/5
                                opacity-0 invisible group-hover:opacity-100 group-hover:visible
                                transition duration-150">
                                    <a href="{% url "create-category" %}" target="__<blank" class="block  px-4 py-2 text-sm hover:bg-gray-700">Create</a>
                                    <a href="{% url "category-list" %}" target="__<blank" class="block  px-4 py-2 text-sm hover:bg-gray-700">View</a>
                            </div>
                        </div>
                    </li>
        {% endif %}

        

        
        <li>
            <form method="POST" action="{% url "logout" %}">
                {% csrf_token %}
                <button type="submit" class="px-2 py-1 bg-white/30 backdrop-blur-sm rounded text-white text-center font-semibold border border-white/50">
                    logout
                </button>
            </form>
        </li> 
        <a href="https://github.com/JUBAYER-AHMMED">
            <li>
                <button class="w-10 h-10 bg-gray-800/30 backdrop-blur-sm rounded-full text-white text-center font-semibold border border-white/50">
                J
                </button>
            </li>
        </a>
    </ul>
    
</body>
</html>

core/templates/no_permission.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>You do not have permission to access this page.</h2>
</body>
</html>

core/templates/non_logged_header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/output.css' %}">
    <script src="{% static 'js/navbar.js' %}"></script>


</head>
<body>
    <header class="relative z-20 mx-6 px-3 py-5 flex justify-between items-center">
        {% comment %} LOGO  {% endcomment %}
        <div class="img flex justify-center items-center">
            <img src=" {% static 'images/logo1.png' %}" alt="" style="width: 50px;">
            <h1 class="text-xl font-semibold text-white">Events</h1>

        </div>

        <button id="hamburgerBtn" class="md:hidden flex flex-col gap-1 p-2">
            <span class="block w-6 h-0.5 bg-white"></span>
            <span class="block w-6 h-0.5 bg-white"></span>
            <span class="block w-6 h-0.5 bg-white"></span>
        </button>

        
        {% comment %} NAVIGATION  {% endcomment %}
        <nav class="hidden md:flex md:gap-4 items-center">
            <ul class="flex flex-col  md:flex-row gap-4  text-white">
               <a href="{% url "home" %}"> <li class="px-2 py-1 rounded-sm hover:bg-white/20 uppercase">Home</li></a>
               <a href=""><li class="px-2 py-1 rounded-sm uppercase hover:bg-white/20">About</li></a>
               <li><button class="p-2 rounded-full relative hover:bg-white/20">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-white">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
                </svg>
                </button></li>
               <a href="{% url "authpage" %}"><li>
                <button class="px-2 py-1 bg-white/30 backdrop-blur-sm rounded-md text-white text-center font-semibold border border-white/50">
                SIGNUP
                </button>
               </li></a>
            </ul>
        </nav>
    </header>
    
    <ul id="navMenu"
    class="hidden flex-col items-center justify-center relative z-30 gap-4
           text-white text-lg text-center md:hidden
           border backdrop-blur-sm border-white/25 bg-white/20 shadow-md p-2">
        <a href="{% url "home" %}"> <li class="px-2 py-1 rounded-sm hover:bg-white/20">HOME</li></a>
        <a href=""><li class="px-2 py-1 rounded-sm hover:bg-white/20">ABOUT</li></a>
        <li class="hover:bg-white/20"><button class="p-2 rounded-full relative hover:bg-white/20">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-white">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
                </svg>
                </button>
        </li>
        <a href="{% url "authpage" %}"><li class="hover:bg-white/20">
                <button class="px-2 py-1 bg-white/30 backdrop-blur-sm rounded-md text-white text-center font-semibold border border-white/50">
                SIGNUP
                </button>
               </li>
        </a>
    </ul>
</body>
</html>